### ISSUE TITLE
GPS time

### ISSUE THREAD

**Issue by bonvech** [nj-vs-vh/sphere-telemetry-processing#1]
Нам нужно доставать из лога время по GPS для синхронизации с полетными данными, в которых время по GPS.

**Comment by bonvech** [comment]
Вполне достаточно выводить GPSstamp - время в формате, как в строке GPS: HHMMSS.
При необходимости его легко преобразовать во время.

**Comment by nj-vs-vh** [comment]
Насколько я понимаю, там нужно делать какую-то интерполяцию по времени записи в бортовом и наземном логе, чтобы получить значения в один момент времени, поэтому я решил сразу сделать всё в подходящем типе.

**Comment by bonvech** [comment]
Можно тогда выводить дополнительную колонку GPSstamp?

**Comment by nj-vs-vh** [comment]
Готово!
